server:
  port: 8900

spring:
  application:
    name: saleseaze-api
  data:
    mongodb:
      uri: mongodb://${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/saleseazedb

app:
  cors:
    allowed-origins: http://localhost:3000

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

keycloak:
  auth-server-url: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8080}/auth
  realm: Saleseaze
  resource: saleseaze-app
  ssl-required: external
  principal-attribute: preferred_username
  use-resource-role-mappings: false

saleseaze:
  redirect-url: http://localhost:3000/*
  default-users:
    super_admin: super@123
    admin: admin@123
    user: user@123

facebook:
  client-id: 855772318691791
  client-secret: df44b1eb7bb25e1934bde8ddbbd347d0
  api-version: v11.0
  base-url: https://graph.facebook.com
  retry-max-attempts: 5
  retry-max-delay: 100

storage:
  api-key: 765198756439666
  api-secret: ENC(ATVWM1McdUAq3cqVlMGc1HXZPEi4Twp672jTo1fhOgid8QFgNiPr7g==)
  cloud-name: saleseaze

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

keycloak-admin:
  user-name: ${KEYCLOAK_ADMIN_USER_NAME:admin}
  pwd: ${KEYCLOAK_ADMIN_PWD:admin}
  client-id: admin-cli
  realm: master


springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC
    disable-swagger-default-url: false

